Metacog/config/routes.rb
Rails.application.routes.draw do
    get '/login' => 'sessions#new'

    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

    get '/signup' => 'users#new'
    post '/users' => 'users#create'

    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Routes for posts
  #Resources :posts
  # resources :posts, only: [:index, :show, :new, :create, :destroy, :edit]
  #Resources for :comments
  # resources :comments, only: [:index, :new, :create, :destroy]

  # resources :subreddits, only: [:index, :new, :show, :create, :edit, :update] do
  #     resources :posts, only: [:index, :show, :new, :create, :destroy, :edit, :update]
  # end
  # resources :posts, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
  #     resources :comments, only: [:index, :new, :create, :destroy]
  # end
  # resource :subreddits, only: [:index, :new, :show, :create, :edit, :update] do
  #     resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  # end
  # resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy]  do
  #     resources :comments, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  # end

  resources :subreddits do
      resources :posts
  end

  resources :posts do
      resources :comments
  end

  # patch '/posts/:id/edit', to: "posts#edit"

  root to: "subreddits#index"

  # "subreddit/:subreddit_id/posts/:post_id/comments/:id", to: "comment#show"


  # get '', to: "posts#index"
  #
  # get "new", to: "posts#new"
  #
  # post 'new', to: 'posts#create'
  #
  # get 'posts/:id', to: 'posts#show'
  #
  # get 'post/:id/edit', to: 'posts#edit'
  #
  # patch 'posts/:id', to: 'posts#update'
  #
  # get 'comments', to: 'comments#index'
  #
  # post 'comment', to: "comments#create"
  #
  # get 'posts/:id/newcomment', to: "comments#new"
  #
  # post 'posts/:id/newcomment', to: "comments#create", as: 'new_comment_path'

  #Routes for delete

  # delete '/post/:id', to: 'posts#destroy'





end

Metacog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Metacog/app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    validates :body, :post_id, presence: true
end

Metacog/app/models/post.rb
class Post < ApplicationRecord

    has_many :comments, dependent: :destroy
    belongs_to :subreddit
    validates :title, :body, presence: true
end

Metacog/app/models/subreddit.rb
class Subreddit < ApplicationRecord
    has_many :posts, dependent: :destroy
    # has_many :comments. through: :posts
end

Metacog/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password, :length => { :minimum => 6 }
    validates_confirmation_of :password
end

Metacog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def authorize
      redirect_to '/login' unless current_user
    end
end

Metacog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # def index
  #     @comments = Comment.all
  # end
  #
  # def new
  #     @comments = Comment.new
  # end

  def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.new(comment_params)

      if @comment.save
          redirect_to(@post)
          flash[:notice] = "Comment saved successfully."
      else
          redirect_to(@post)
          flash[:notice] = "Comment could not be saved."
      end
  end

  def destroy
    @post = Post.find(params[:post_id])

    # @comment = @post.comments.new(comment_params)
    # @post.comments.find(params[:id]).destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    flash[:success] = "Comment deleted"
    redirect_to(@post)
  end


  # Comment params
  private
  def comment_params
      params.require(:comment).permit(:body)
  end

end

Metacog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
      @posts = Post.all()
  end

  def new
      @post = Post.new
  end

  def create
      @subreddit = Subreddit.find(params[:subreddit_id])
      @post = @subreddit.posts.new(post_params)

      if @post.save
        #   redirect_to(controller: "posts", action: "show", id: @post.id)
        redirect_to(@subreddit)
      else
          redirect_to(new_subreddits_post_url)
          flash[:notice] = "Post could not be saved."
      end
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.new
  end

  def edit
      @post = Post.find(params[:id])
  end

  def update
     @post = Post.find(params[:id])
     @post.update_attributes(post_params)
     redirect_to post_path
  end


  # def delete
  #     @post = Post.find(params[:id])
  # end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Post deleted"
    redirect_to('')
  end


private

  def post_params
      params.require(:post).permit(:title, :body)
  end
end

Metacog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
       user = User.find_by_email(params[:email])
       if user && user.authenticate(params[:password])
         session[:user_id] = user.id
         redirect_to '/'
       else
         redirect_to '/login'
       end
     end

     def destroy
       session[:user_id] = nil
       redirect_to '/login'
     end
end

Metacog/app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController

    before_filter :authorize
    
    def index
        @subreddits = Subreddit.all
    end

  def new
      @subreddit = Subreddit.new
  end

  def show
      @subreddit = Subreddit.find(params[:id])
      @post = @subreddit.posts.new
  end

  def edit
      @subreddit = Subreddit.find(params[:id])
  end

  def update
      @subreddit = Subreddit.find(params[:id])
      @subreddit.update_attributes(subreddit_params)
      redirect_to(action: "show", id: @subreddit.id)
  end

  def create
      @subreddit = Subreddit.create(subreddit_params)
      redirect_to(controller: "subreddits", action: "show", id: @subreddit.id)
  end

  private

  def subreddit_params
      params.require(:subreddit).permit(:name, :description)
  end

end

Metacog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user = User.new
  end

  def create
   user = User.new(user_params)
   if user.save
     session[:user_id] = user.id
     redirect_to '/'
   else
     redirect_to '/signup'
   end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

Metacog/app/helpers/application_helper.rb
module ApplicationHelper
end

Metacog/app/helpers/comments_helper.rb
module CommentsHelper
end

Metacog/app/helpers/posts_helper.rb
module PostsHelper
end

Metacog/app/helpers/sessions_helper.rb
module SessionsHelper
end

Metacog/app/helpers/subreddits_helper.rb
module SubredditsHelper
end

Metacog/app/helpers/users_helper.rb
module UsersHelper
end

Metacog/app/views/comments/index.html.erb
<legend>MetaCog</legend>
<div class="container">
    <!--
        <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
            <p>comment Content</p>
        </div>
    </div>
    -->
    

    <div class="row">
        <a class="col-lg-12" href="/comments/new">New comment</a>
    </div>
</div>

Metacog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Metacog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Metacog/app/views/posts/edit.html.erb
<div class="container">
    <%= form_for @post do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :body %><br>
        <%= f.text_area :body %>
    </p>

    <p>
        <%= f.submit 'Submit' %>
    </p>
    <% end %>    
</div>

Metacog/app/views/posts/index.html.erb
<legend>MetaCog</legend>
<div class="container">
    <!-- <div class="row">
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3">
            <p>Post Title</p>
        </div>
        <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
            <p>Post Content</p>
        </div>
    </div> -->
    <div class="postsContainer container">
        <% @posts.each do |post| %>
            <%= link_to post, controller: "posts", action: "show", id: post do  %>
            <div class="row">
                <div class="postTitle col-sm-3">
                    <%= post.title %>
                </div>
                <div class="postBody col-sm-9">
                    <%= post.body %>
                </div>
            </div>
            <% end %>
        <% end %>
    </div>

    <div class="row">
        <a class="col-lg-12" href="/posts/new">New Post</a>
    </div>
</div>

Metacog/app/views/posts/new.html.erb
<legend>New Post</legend>


<%= form_for [@subreddit, @post] do |f| %>
<h4>New Post</h4>
<div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :body %>
    <%= f.text_field :body %>
</div>
<div class="text-xs-right">
    <%= submit_tag "Submit", class: 'btn btn-default' %>
</div>
<% end %>

Metacog/app/views/posts/show.html.erb
<!-- <legend>Show Post</legend> -->
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <p><a href="/">Back</a></p>
            <h4><%= @post.title %></h4>
            <p><%= @post.body %></p>
            <hr>
            <div class="btn-group btn-group-justified">
                <div class="btn-group">
                    <button type="button" class="btn btn-default">Save</button>
                </div>
                <div class="btn-group" role="group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        More
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><%= link_to 'Edit', edit_post_path(@post) %></a>
                        </li>
                        <li>
                            <a href="#"><%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "You sure?" } %></a>
                        </li>
                    </ul>
                </div>
            </div>
            <hr>
            <%= form_for [@post, @comment] do |f| %>
                <h4>Comments</h4>
                <div class="form-group">
                    <%= f.text_area :body, class:"form-control" %>
                </div>
                <div class="text-xs-right">
                    <%= submit_tag "Submit", class: 'btn btn-default' %>
                </div>
            <% end %>
            <hr>
            <% @post.comments[0..-2].each do |c| %>
                <p><%= c.body %></p>
                    <%= link_to "Delete", post_comment_path(c.id, :post_id => c.post_id), method: :delete, data: { confirm: "You sure?" } %>
            <% end %>
        </div>
    </div>
</div>

Metacog/app/views/subreddits/create.html.erb
<h1>Subreddits#create</h1>
<p>Find me in app/views/subreddits/create.html.erb</p>

Metacog/app/views/subreddits/edit.html.erb
<div class="container">
    <h1><%= @subreddit.name %></h1>
    <%= form_for @subreddit do |f| %>
    <p>
        <%= f.label :description %><br>
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.submit 'Submit' %>
    </p>
    <% end %>
</div>

Metacog/app/views/subreddits/index.html.erb
<h1>Subreddits</h1>
<div class="container">
    <% @subreddits.each do |subreddit| %>
        <%= link_to subreddit.name, controller: "subreddits", action: "show", id: subreddit   %>
        <div class="row">
            <div class="postBody col-sm-9">
                <%= subreddit.description %>
            </div>
        </div>
        <hr>
    <% end %>
</div>

Metacog/app/views/subreddits/new.html.erb
<%= form_for(@subreddit) do |s| %>
<h4>Subreddits</h4>
<div class="form-group">
    <%= s.text_field :name, class:"form-control" %>
    <hr>
    <%= s.text_area :description, class:"form-control" %>
</div>
<div class="text-xs-right">
    <%= submit_tag "Submit", class: 'btn btn-default' %>
</div>
<% end %>

Metacog/app/views/subreddits/show.html.erb
<!-- <legend><%=@subreddit.name %></legend> -->
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <p>
                <a href="/">Back</a>
            </p>
            <h4><%= @subreddit.name %></h4>
            <p><%= @subreddit.description %></p>
            <hr>
            <div class="btn-group btn-group-justified">
                <div class="btn-group">
                    <button type="button" class="btn btn-default">Save</button>
                </div>
                <div class="btn-group" role="group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        More
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><%= link_to 'Edit', edit_subreddit_path(@subreddit) %></a>
                        </li>
                    </ul>
                </div>
            </div>
            <hr>
            <h4>Posts</h4>
            <hr>
            <%= form_for [@subreddit, @post] do |p| %>
            <div class="form-group">
                <%= p.label :title %>
                <%= p.text_field :title %>
                <%= p.label :body %>
                <%= p.text_field :body %>
            </div>
            <div class="text-xs-right">
                <%= submit_tag "Submit", class: 'btn btn-default' %>
            </div>
            <% end %>
            <!-- <%= link_to "Add Post", :action=>"new", :controller=>"posts", :subreddit_id=>"1"  %> -->
            <% @subreddit.posts[0..-2].each do |post| %>
                <!-- <%= link_to post, controller: "posts", action: "show", id: post do  %> -->
                <div class="row">
                    <div class="postTitle col-sm-3">
                        <%= link_to post.title, controller: "posts", action: "show", id: post   %>
                        <!-- <%= post.title %> -->
                    </div>
                    <div class="postBody col-sm-9">
                        <%= post.body %>
                    </div>
                </div>
                <% end %>
            <% end %>
            </div>

            <!-- <div class="row">
                <%= link_to @subreddit.posts, controller: "posts", action: "new" %>
            </div> -->

Metacog/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

Metacog/app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for(@user) do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>